### ISSUE TITLE
Worldmap doesn't show colors on all OPs

### ISSUE THREAD

**Issue by Wilworin** [Neocron-Classic/pre-release-issues#104]
So, when looking at the world map it doesn't show any colors at all OPs.
![image](https://user-images.githubusercontent.com/75475031/189547030-0e239f09-7c83-452b-b76c-8fc634d3f559.png)

However, when I check the Terminal at INFO->OUTPOST they are all occupied.
![image](https://user-images.githubusercontent.com/75475031/189547055-57f2d72a-d5a1-4d62-82d1-2b3c4872d41d.png)
![image](https://user-images.githubusercontent.com/75475031/189547069-c3bc8842-3ba9-4da1-8bc2-9c3fe20b2145.png)

**Comment by Jestunhi** [comment]
Closed as also reported in #190 (which is more recent, but it also reports various other things so easier to close this one!)
