### ISSUE TITLE
Aimbot for Free? :-D Need to fix 

### ISSUE THREAD

**Issue by Blackeast** [Neocron-Classic/pre-release-issues#108]
Good day together.

We got yesterday from a dev.
no idea which one that was. the info that we can adjust the size of UI elements in the "settings.toml" file.

Now one of us noticed that "Targetbox" and "Crosshair" are also in there. And when we try it, we almost find that changing it to 5+ feels like an aimbot or even a hack.

You should look over there.

Being able to resize the UI elements is Good for 4K resolution.
But "Targetbox" and "Crosshair" have no place there.

![Back](https://user-images.githubusercontent.com/35923077/189687071-f0e56899-fa1c-48c1-ba95-2da6f0048039.PNG)
![shot0001](https://user-images.githubusercontent.com/35923077/189687111-0a1f556c-82c7-46f5-8c1f-8392f9cb4d98.png)

https://www.youtube.com/watch?v=EYHs3LeGsak

**Comment by Blackeast** [comment]
https://www.youtube.com/watch?v=EYHs3LeGsak

**Comment by NCC-Lykos** [comment]
It does not increase the hitbox size, it scales the text. The hitbox and crosshair still act the same at 1.0 as they do at 5.0.
