### ISSUE TITLE
Copbot rifle ammo

### ISSUE THREAD

**Issue by Jestunhi** [Neocron-Classic/pre-release-issues#111]
If the recent changes are a starting point for making the copbot rifle usable can the tl on the ammo please be looked at so it can be recycled.

![image](https://user-images.githubusercontent.com/112770725/189743187-6f82f317-2d39-4255-afb4-6de0088e6cfa.png)

**Comment by NCC-Therenall** [comment]
The intent with this was that it isn't able to be constructed or recycled, it's drop only. Closing for now.
