### ISSUE TITLE
Apartment Keys?

### ISSUE THREAD

**Issue by hazuk** [Neocron-Classic/pre-release-issues#114]
The trader in Peper 3 dont sell Outzone Apartment Keys.

**Comment by hazuk** [comment]
and some Sleazy Apartment Locations are missing

**Comment by hazuk** [comment]
and Keys for this new location in pp1 ?

**Comment by NCC-Gnisha** [comment]
> 

Which apartments are missing? I'm going to get all of this fixed up tomorrow.

**Comment by hazuk** [comment]
Skansy says in TG you cant find a trader for apartment keys

**Comment by hazuk** [comment]
In Tech Haven i cant find a Trader for Apartment keys.

**Comment by NCC-Gnisha** [comment]
I've confirmed there is an NPC selling Tech Haven apartment keys in Tech Haven SEC-2

![THAptVendor](https://user-images.githubusercontent.com/32779211/190846769-1cd90ea6-238b-4ed5-a031-04fcd93d2c36.png)

**Comment by NCC-Gnisha** [comment]
I've confirmed there is an NPC selling Canyon apartment keys in the Canyon.

![TGAptVendor](https://user-images.githubusercontent.com/32779211/190846938-50779947-29ca-4c7a-866f-7ea9f57b46c3.png)

**Comment by NCC-Gnisha** [comment]
Other issues have been fixed and submitted for patching.
