### ISSUE TITLE
Idea how the const cap could determined

### ISSUE THREAD

**Issue by tuxhomer** [Neocron-Classic/pre-release-issues#115]
I'm working with the formula from this side : https://forum.neocron-game.com/showthread.php?132763-Construction-Guide

Example 1:
My fresh made Conster have 5 INT, 3 DEX and 64 CST.

(0.1*DEX) + (0.2*INT) + (0.7*CST) = Real construction skill 
so my Conster have a real cst skill of  46,1 (0.3 + 1+ 44,8 = 46,1).
Lets say to reach the build cap you need 2 times the techlevel.
The best my conster can make is a techlevel 23 weapon at build cap.
He can const weapons till TL 46, but at lower build quality.

Example 2:
A spy with 68 INT, 81 DEX and 60 CST.

The real cst skill is  63,7 (8,1 + 13,6 + 42 = 63,7).
Build cap is till TL31 and can make weapons till TL60 with lower quality, because of the 60 CST.

Example 3:
A spy with 80 INT, 70 DEX and 150 CST.

The real cst skill is 128.
TL build cap is 64 and the max TL with lower quality is 128.

**Comment by Jestunhi** [comment]
This would make csting much easier at low levels where you have the fraction of the intelligence as a tank but expect to be able to max out crafing for dozens of TLs higher than you can use.

It would make csting much harder at high levels where you'd need significantly more cst than with the current system to max out stats.

Essentially this change makes it much easier to make an alt to provide your characters with weapons and harder to be an actual high level, dedicated constructor. I don't feel this is the direction which constructing should go.

**Comment by Norcoen-gif** [comment]
This refers to the current issue that vendor items have a too high quality.
It all resolves when the vendor items are returned to their original value, because your earlygame constructors will then be able to offer a useful service, even without capping up to tl23 items at a fresh start...
No need to redo the whole formular in my opinion.
