### ISSUE TITLE
LE not usable at /25

### ISSUE THREAD

**Issue by Jestunhi** [Neocron-Classic/pre-release-issues#117]
Not sure if the rquirements are bugged, or the item description just needs updating.

![image](https://user-images.githubusercontent.com/112770725/189987967-0ed66cd9-dbc0-4c3b-92ed-93124c4cbf87.png)

**Comment by NCC-Therenall** [comment]
This should be looked at for the new leveling system as well.

**Comment by ghost** [comment]
This bug was created before the updates to the skill/leveling system. I have confirmed that the re-implant requirements of the LE are as programmed.

**Comment by ghost** [comment]
Did fix a bug in the source though!
