### ISSUE TITLE
The game doesn't memorize the "/set gfx_hudcolor x" parameter - Resets after each login

### ISSUE THREAD

**Issue by Dreaminpastels** [Neocron-Classic/pre-release-issues#12]
I usually roll with /set gfx_hudcolor 2 but the game will reset it to default after each login

After typing the command:
![image](https://user-images.githubusercontent.com/112765280/188273588-0daf3291-0e46-46e8-b077-aec4ed739ab9.png)
After relogging:
![image](https://user-images.githubusercontent.com/112765280/188273611-fa6ec010-a33e-474f-9d1e-82532bd9de65.png)

**Comment by NCC-Therenall** [comment]
Fixed this, should be patched in next path.
