### ISSUE TITLE
SMS commands do not work

### ISSUE THREAD

**Issue by Dreaminpastels** [Neocron-Classic/pre-release-issues#13]
After setting +sms command, the game won't execute them properly after either through a "/sms x" command or by pressing ALT+V then pressing the corresponding key

![image](https://user-images.githubusercontent.com/112765280/188273680-1295f3ee-e021-428c-a99b-4d3804fe63cc.png)

**Comment by NCC-Therenall** [comment]
This will be fixed in the next patch, I had forgot to write the SMS back to the config after it got set.
