### ISSUE TITLE
BioTech Epic mission 4 issues

### ISSUE THREAD

**Issue by tuxhomer** [Neocron-Classic/pre-release-issues#130]
according to the Wiki page, https://wiki.neocron.org/wiki/EpicGuide:BioTech , you have to kill one TG npc but
i had to kill 3 of them at  PP3.

Mission 4 is a */35 mission.
The TG npcs are level 60/60. it would be impossible to finish the misson at */35.

**Comment by hazuk** [comment]
just edit the wiki page ? and fix it @tuxhomer

**Comment by NCC-Gnisha** [comment]
@tuxhomer Does the in-game mission text properly reflect what you have to kill?

**Comment by tuxhomer** [comment]
@NCC-Gnisha  not sure. Could be kill one TG npc

**Comment by NCC-Gnisha** [comment]
Fixed. I'll be pushing up quite a few content updates in the next few days so it may be a few days before you see this live.
