### ISSUE TITLE
Paratemol Forte and other drugs of that tier sold in outposts

### ISSUE THREAD

**Issue by Jestunhi** [Neocron-Classic/pre-release-issues#131]
Potential mismatch from patch 200, unsure if intentional or mistake.

Yo's in Simmons Outpost is selling Paratemol Forte.

![image](https://user-images.githubusercontent.com/112770725/190216159-0dfc918c-3566-4170-ac52-1bf5f502d879.png)

Based on the patch 200 notes this should be limited to smugglers only and removed from outposts.

![image](https://user-images.githubusercontent.com/112770725/190215555-717ca019-1d50-49b5-9cc6-e0712bf51356.png)

Supported by patch 198 / 199 patch notes which explain which tiers of drugs have been removed from Medicare vendors.

![image](https://user-images.githubusercontent.com/112770725/190215748-ebb3f652-1c98-4226-aec7-00e5e6b671c0.png)

Since these drugs have been removed from Medicare I'm assuming they are ones which should not be sold at outposts.

(Patch notes link: http://neocron.dk/?action=patch)

**Comment by hazuk** [comment]
Secret Passage should be cheap drugs for Black Dragon !
TG & MB should be High Price!
and all Other Drugdealer should be Removed!

**Comment by NCC-Gnisha** [comment]
This is intended behavior.
