### ISSUE TITLE
Black Dragon Epic Apartment Genrep - You are hostile to the local faction. Activation of this Genrep denied.

### ISSUE THREAD

**Issue by hazuk** [Neocron-Classic/pre-release-issues#133]
The Genrep from the Black Dragon Epic Apartment cant be activated!
Message in Chat says:
You are hostile to the local faction. Activation of this Genrep denied.
![image](https://user-images.githubusercontent.com/32795552/190337602-554539a3-da7d-40da-ae7c-384fcd922c92.png)

**Comment by NCC-Gnisha** [comment]
What zone is your lift in?

**Comment by hazuk** [comment]
Pepper Park / Black Dragon
https://cdn.discordapp.com/attachments/1019342095254835340/1020306555868033054/111333.jpg

**Comment by NCC-Gnisha** [comment]
Fixed in next patch.
