### ISSUE TITLE
HEW 'Burner' RC275 has the NC2 Model

### ISSUE THREAD

**Issue by tuxhomer** [Neocron-Classic/pre-release-issues#137]
![shot0023](https://user-images.githubusercontent.com/13179348/190535579-2b94b6ad-2338-4928-ba2a-994bbd11d1e0.png)
![shot0024](https://user-images.githubusercontent.com/13179348/190535580-3d680fc1-d16e-4499-9569-20db65ef247e.png)

**Comment by ghost** [comment]
Fixed.
