### ISSUE TITLE
Plaza 3 Ghost Taxi / Police Drone (Visual)

### ISSUE THREAD

**Issue by nIdzzlll** [Neocron-Classic/pre-release-issues#139]
[Tested 2022-09-15]

Location: Plaza 3 above the HEW shop near the fashion store

![P3-Ghost-Taxi-Position](https://user-images.githubusercontent.com/113188846/190499603-e630e308-a951-4950-8dc2-e43c7d18af85.jpg)

Animation GIF, actual timedelay slower:
![2022-09-15 21-37-23](https://user-images.githubusercontent.com/113188846/190499623-af1c4b03-1901-4ce2-9c94-890ee839876a.gif)

Issue: Every few seconds a Taxi / Police Drone? appears for a frame or two in the spot indicated above. Viewing position does not seem to matter. Bug was also observed by user “hazuk” in fullscreen. User “Cryton” could not see it but also had vendors not display their inventory (may not be related).

Mitigation: These things used to roam around Plaza 3 and may have not been completely removed. Maybe some script is still running its code.

**Comment by NCC-Lykos** [comment]
Recompiled Plaza 3 to fix this issue, will be good in next patch.
