### ISSUE TITLE
UI Help System (GM Support) description

### ISSUE THREAD

**Issue by nIdzzlll** [Neocron-Classic/pre-release-issues#140]
[Tested 2022-09-15]

Function: In-game support help menu (“?” Upper right corner) HELPSYSTEM

![UI-Bugtracker-Report-A-Bug](https://user-images.githubusercontent.com/113188846/190483939-62d3575b-01ce-48ac-be4a-9906b9e85aa7.jpg)

Issue: Text reads […]“If you only want to describe a bug you’ve found click ‘REPORT A BUG’, a new form would be displayed”. There is no “REPORT A BUG” button.

Mitigation: Change wording to “click ‘BUGTRACKER’”. If this in-game Bugtracker is not monitored, inform players to visit the Github issue-tracker or Discord linked (invite code may change) on the neocron.org website

**Comment by NCC-Gnisha** [comment]
Fixed. Submitted for patching.
