### ISSUE TITLE
UI: Consumable Item Effects font size (Details) not scalable.

### ISSUE THREAD

**Issue by nIdzzlll** [Neocron-Classic/pre-release-issues#145]
Item; Drugs - Paratemol Forte (4 Effects)
[Tested 2022-09-14]

![DrugsUi-1920x1080-FS](https://user-images.githubusercontent.com/113188846/190264240-39b5d8ce-a250-401a-bb61-59312e4c9314.jpg)

Issue: 4+ status effects text misalignment when client used rpos.scale 1.5 in settings.toml. Displays correctly with default 1.0 scale. May apply to other items that have multiple effects (not tested)

Tested resolutions 
2560x1440 Borderless & Fullscreen
1920x1080 Borderless & Fullscreen

Mitigation: Only visual bug. Exclude corresponding scaling option in settings.toml (HELPTEXTWINDOW?)

**Comment by NCC-Gnisha** [comment]
Fixed. Submitted for patching.
