### ISSUE TITLE
Gameworld: Outzone world issues 

### ISSUE THREAD

**Issue by Zmiler7** [Neocron-Classic/pre-release-issues#146]
![shot0017](https://user-images.githubusercontent.com/112765764/190716030-b18af073-ec6f-4934-9dcf-eb01d4208bde.png)
Legacy Issue - Steps dont work 

![shot0016](https://user-images.githubusercontent.com/112765764/190716101-d440a50b-b5dd-4ffe-84f3-771c7db4f3ca.png)
Easy to get stuck in door opening too close 

![shot0015](https://user-images.githubusercontent.com/112765764/190716199-7df5c82e-1c60-452a-a7f1-c62b5a23f09b.png)
Legacy issue? - Doors have never opened

![shot0013](https://user-images.githubusercontent.com/112765764/190716301-ff24a919-e22d-4fe5-bc6f-014e2227e8e5.png)
Impossible to access Supply Box 

![shot0009](https://user-images.githubusercontent.com/112765764/190716398-e94feba5-4f1c-4950-baf8-61400f383228.png)
Texture

**Comment by NCC-Lykos** [comment]
Recompiled OZ3 to fix ladder.

Those doors go nowhere, working as intended.

Supply box is decoration only, working as intended.

That texture is like covering an opening with a board, working as intended.
