### ISSUE TITLE
Gameworld - Ind Sec 2 Traders selling same items

### ISSUE THREAD

**Issue by Zmiler7** [Neocron-Classic/pre-release-issues#147]
![shot0012](https://user-images.githubusercontent.com/112765764/190716626-e0402708-8105-4df4-8761-5034104f7447.png)
![shot0011](https://user-images.githubusercontent.com/112765764/190716648-f055978c-8860-479a-ba4e-e31edb3a2775.png)
![shot0010](https://user-images.githubusercontent.com/112765764/190716657-f0887863-9e1f-4799-8ba7-fb305f039c8a.png)

Of the 4 Traders in this part of Ind Sec 2, 3 of them sell same items. 1 Sells for cheaper than other two

**Comment by ghost** [comment]
Fixed.
