### ISSUE TITLE
Sometimes the crytons vendors in plaza (and probably other places are empty

### ISSUE THREAD

**Issue by tjbhan** [Neocron-Classic/pre-release-issues#150]
![2022-09-17_15h50_09](https://user-images.githubusercontent.com/64246483/190860484-b71a4551-4f2b-4cdc-8371-659573e5cf48.png)

**Comment by NCC-Lykos** [comment]
Where are you located?

**Comment by NCC-Therenall** [comment]
This is weird, I've never seen this. Is anyone else getting this?

**Comment by NCC-Lykos** [comment]
Closed with lack of information
