### ISSUE TITLE
SUGGESTION - Can we have Citycom access from our RPOS?

### ISSUE THREAD

**Issue by Jestunhi** [Neocron-Classic/pre-release-issues#151]
From a lore perspective: We have communication that works anywhere in the wastes, we get paid for each enemy we kill even in the deepest caves, we have GPS and real-time faction sympathies. And when we complete a mission that's tracked when away from a citycom. Why do we need to physically use extra hardware to access a citycom?

From a gameplay perspective: It limits the optimal levelling spots - it's why the general levelling experience is Aggies & Launchers. You can easily get those missions and kill what needs killing. This may change somewhat if we get the new levelling system and suddenly missions are no longer a requirement for monk dex, tank psi, etc. But even then there's more encouragement to try new spots if you're also able to efficiently do missions there.

**Comment by NCC-Gnisha** [comment]
Won't happen.
