### ISSUE TITLE
Apt Lift Buttons Have no Hover Effect

### ISSUE THREAD

**Issue by EvilHogg** [Neocron-Classic/pre-release-issues#158]
There is no hover effect when you hover over the apt menu buttons. All other menu buttons have effects.

"OK" button probably should not exist when the menu opens from inside an apt.

![apt_complex_buttons](https://user-images.githubusercontent.com/34963912/190935546-69de5c51-3355-4398-ab0b-40174cb25401.png)

**Comment by NCC-Gnisha** [comment]
Fixed. Submitted for patching.
