### ISSUE TITLE
P1 Lamps Missing Effect, Effect Missing Lamp

### ISSUE THREAD

**Issue by EvilHogg** [Neocron-Classic/pre-release-issues#162]
2nd FL on the way to the apts.

Effect with no lamp:

![p1_2nd_fl_light](https://user-images.githubusercontent.com/34963912/191132699-b4abcfbd-964e-4ec2-8cc7-5fefe3d2dca1.png)

Lamp with no effect:

![p1_2nd_fl_light_no_affect](https://user-images.githubusercontent.com/34963912/191132717-b4997776-9204-4c4c-b887-bbcd79eef208.png)

**Comment by NCC-Lykos** [comment]
Fixed in next patch
