### ISSUE TITLE
Escape Sync / Fast Relog to Reset NPCs

### ISSUE THREAD

**Issue by hazuk** [Neocron-Classic/pre-release-issues#165]
Escape Sync need to be removed!
I know some Players they abuse it everytime to travel faster,its like a free teleport cheat

-Travel in the wastelands
-Sync in to the next zone.
-Press Escape while in the Sync.
-You now in the login screen.
-Press Resume in login screen.
-You been Teleported to the /set reset_position 1 position of a zone! (most time the position is in the middle of a sector!)

It can be used as a advantage in pvp or other situations.

found some old patchnotes.... seems like the fix for vehicles worked but not for the player.

nc beta patch 180
- Improved the zone change code. Players should no longer appear at the reset positions if they log out during the zone change. The same should apply to vehicles.

**Comment by hazuk** [comment]
Fast Relog to reset the aggro from NPC´s is a big Problem too!
The aggro should be reseted after 10sec+ and not after 1sec in login screen.

Example: Mc5 Base Commander Farming.
-Run inside the Room.
-Search the Commander
-Hide near to Commander
-Do a fast Relog
-Aggro should be reseted from all NPCs in the Zone.
-Go Pull the Commander SOLO and get some easy parts.
-Reset Zone and do it all over again.
These Relog stuff can be used at many places in the game.

**Comment by NCC-Therenall** [comment]
The esc sync was removed, though still needs some improvements. I wasn't aware of the vehicle part, I may look into that for those improvements.

**Comment by ghost** [comment]
> The esc sync was removed, though still needs some improvements. I wasn't aware of the vehicle part, I may look into that for those improvements.

esc sync is fixed we tryd it many times good job @NCC-Therenall 👍
