### ISSUE TITLE
floating box in g13

### ISSUE THREAD

**Issue by hazuk** [Neocron-Classic/pre-release-issues#166]
floating box in g13 see screenshot for location.
https://gyazo.com/789fef9e9121df95a4a0f9d3f3463f7b

**Comment by NCC-Therenall** [comment]
Embedding the image so we don't have to go to another page:

![image](https://user-images.githubusercontent.com/32750893/198047050-7355bcec-13d3-4500-b151-94dd1337582d.png)

**Comment by ghost** [comment]
Something heavy has been added to the box to weigh it down.
