### ISSUE TITLE
Swamp Cave 3

### ISSUE THREAD

**Issue by Liquidous** [Neocron-Classic/pre-release-issues#170]
Inside the Swamp cave is a NPC with no name , PE skin. If you shoot her you sync out of game and need to relog in. Tried it 3 times to confirm..
![SwampCavePE](https://user-images.githubusercontent.com/113066151/191636746-7b70431d-ae10-42ed-8665-21f74482e50e.jpg)

**Comment by hazuk** [comment]
@Liquidous  you crashed the whole server with it :D

**Comment by hazuk** [comment]
> @hazuk I logged right back in , did the server kick you 3 times? I am in now

yes 3 times

**Comment by NCC-Gnisha** [comment]
NPC deleted
