### ISSUE TITLE
Cryton´s Plaza 1 sells 2x TL30 Hacktool

### ISSUE THREAD

**Issue by hazuk** [Neocron-Classic/pre-release-issues#175]
Crytons Plaza 1 sells 2x TL30 Hacktool with diffrent prices
![44](https://user-images.githubusercontent.com/32795552/191866498-fb664307-6454-4711-a08a-3a6fe1a475b7.jpg)
![455](https://user-images.githubusercontent.com/32795552/191866502-79edf374-9450-4c39-8805-42e7a356302c.jpg)

**Comment by NCC-Gnisha** [comment]
Fixed. Submitted for patching.
