### ISSUE TITLE
Trader Camp in A-10

### ISSUE THREAD

**Issue by hazuk** [Neocron-Classic/pre-release-issues#176]
there is a Trader Camp in A-10 with 4 Guys they all sell wrong stuff !

Example: 
Weapon Stuff Trader sells Implants.
Drug Trader sells Barkeeper items and so on.

![image](https://user-images.githubusercontent.com/32795552/191867737-a754706f-7fd8-427e-b16e-c6815871f282.png)

**Comment by ghost** [comment]
Fixed.
