### ISSUE TITLE
Recycling the Doy eyes don't work

### ISSUE THREAD

**Issue by tuxhomer** [Neocron-Classic/pre-release-issues#180]
I tried to recycle the doy eyes. it don't work.
The recycling recipes are from this side: 
https://web.archive.org/web/20060520053024/http://www.sheriff-hardy.de/recycling.htm

DOY Material Analyser:
1x Discharged Powersupply, 1x damaged Processor Framework, 1x Bunsh of melted Wires, 1x Broken Sensor Device

DOY Retina Repair Coordinator:
1x melted Entrails, 1x Arm of a Worrior, 1x Mysertious broken Implant, 1x Hair of a Warrior

DOY Vehicle Coordination Linkage:
1x Melted Laser Device, 1x Optical Identification Sensor, 1x Internal Motion Sensor, 1x Disfunction Power Supply

NCC is based on Patch #200 or #201.
But the recycling recipes are got fixed with Test Patch #206.
https://web.archive.org/web/20050128072731/http://nc.synergyxr.net/patchnote.php?id=67 <-- Patch Notes for the Test Patch #206.

Please fix it.

**Comment by tuxhomer** [comment]
And yes, i tested it with other combinations, with the  materials  for f the doy eyes, as well

**Comment by NCC-Gnisha** [comment]
So any test server patches are not "official", also just because we used Patch Level 200 as a base for our version does NOT mean that everything will reflect PL200.  We have, are, and will make changes that differ from PL200. Everyone holding everything to a PL200 standard, please stop.

**Comment by NCC-Gnisha** [comment]
Current recipes for DoY Eyes:

![DoY Eyes Recycle List](https://user-images.githubusercontent.com/32779211/192111910-b649660f-36d5-4fd9-aa31-d23771647c4c.png)

**Comment by NCC-Gnisha** [comment]
I am investigating why the recycle wont start with the proper parts though.

**Comment by NCC-Gnisha** [comment]
Fixed. Submitted for patching.
