### ISSUE TITLE
MC5 Problem

### ISSUE THREAD

**Issue by littlesurf** [Neocron-Classic/pre-release-issues#188]
Just when we kill MC5 commander (3times) first time he have loot a part, two other time he just desapear instantly before we can loot him, don't know if its normal or if its a bug.

**Comment by NCC-Therenall** [comment]
Did you happen to kill him right at 00:00 the two times he disappeared?

**Comment by littlesurf** [comment]
Don’t know who have sent you an issue but it was not me 😉

De : ***@***.***>
Envoyé le :mercredi 26 octobre 2022 15:49
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [Neocron-Classic/pre-release-issues] MC5 Problem (Issue #188)


Did you happen to kill him right at 00:00 the two times he disappeared?

**Comment by NCC-Therenall** [comment]
Well it was sent with your name lol 🤷‍♂️
