### ISSUE TITLE
TG-275 FREEDOM STRIKE not working.

### ISSUE THREAD

**Issue by hazuk** [Neocron-Classic/pre-release-issues#191]
The Epic Granate from the TG Epic is not working.It stucks in hands nothing happens when you click attack
TG-275 FREEDOM STRIKE
![555](https://user-images.githubusercontent.com/32795552/192169363-4c0d012e-bae4-4202-8a12-56a049391a07.jpg)

**Comment by ghost** [comment]
Unable to duplicate this on the current patch.
