### ISSUE TITLE
DRE Epic Apartment - Genrep 

### ISSUE THREAD

**Issue by hazuk** [Neocron-Classic/pre-release-issues#192]
The Genrep from the DRE Epic Apartment cant be activated.
![image](https://user-images.githubusercontent.com/32795552/192169649-fa5e7616-f687-44e4-9aa0-3947a95ece61.png)

Im Black Dragon so im a Enemy yes but shouldnt it be available for all factions to activate this genrep?

**Comment by NCC-Gnisha** [comment]
If the apartment lift is within a zone that you are hostile towards, you cannot activate that GR as Primary.
