### ISSUE TITLE
Traders in H-06 sell wrong items.

### ISSUE THREAD

**Issue by hazuk** [Neocron-Classic/pre-release-issues#197]
there are  3 Guys in H-06 they all sell wrong stuff !

Example:
Weapon Stuff Trader sells Implants.
Drug Trader sells Barkeeper items and so on.

![image](https://user-images.githubusercontent.com/32795552/192909838-6576b310-6fe1-4311-a11b-405f9558bedb.png)

**Comment by ghost** [comment]
Fixed.
