### ISSUE TITLE
Login Screen Background Picture 2560*1440x32 

### ISSUE THREAD

**Issue by hazuk** [Neocron-Classic/pre-release-issues#2]
The login screen background picture is a bit out of place in 2560*1440x32 !
see screenshot
![image](https://user-images.githubusercontent.com/32795552/188248934-56738cc6-2685-4235-89a9-52e348eff391.png)

**Comment by Jestunhi** [comment]
Same issue in 4k, cut off in exactly the same place.

**Comment by hazuk** [comment]
can you add the standart rpos scale 1.4 to resolution 2560 and above ?? It is Impossible to read stuff at standart 1.0 ! New Player´s will have a hard time without knowing they need to change it by there self.

sorry for bad english i hope you know what im talking about :D

**Comment by hazuk** [comment]
[rpos]
	[rpos.scale]
		VEHICLESEAT = 1.4
		SKILL = 1.4
		NAVRAYWINDOW = 1.4
		HYPERCOM = 1.4
		RESPAWNWINDOW = 1.4
		INVENTORY = 1.4
		ARMOR = 1.4
		TARGETBOX = 1.4
		MISSIONINFO = 1.4
		MISCWINDOW = 1.4
		EXITAPPARTMENT = 1.4
		DIALOG = 1.4
		IMPLANTS = 1.4
		TOOLTIP = 1.4
		TEAMWINDOW = 1.4
		NAVRAYARROW = 1.4
		NAVRAYPATH = 1.4
		TUTORIAL = 1.4
		STATUS = 1.4
		CURSOR = 1.4
		QUICKACCESS = 1.4
		BOTTOMBAR_VERTICAL = 1.4
		TOPBAR_VERTICAL = 1.4
		CHAT = 1.4
		PEOPLE = 1.4
		PROCESSOR = 1.4
		QUICKTIPS = 1.4
		SPLITMOVE = 1.4
		REPLICATORWINDOW = 1.4
		CROSSHAIR = 1.4
		ZONEMAP = 1.4
		COMPASS = 1.4
		MINIMAP = 1.4
		MENUBAR = 1.4
		CONTAINER = 1.4
		VEHICALSTATUS = 1.4
		GOGO = 1.4
		HELPTEXTWINDOW = 1.4
		TERMINAL = 1.4
		BUFF = 1.4
		ENTERCODE = 1.4
		FACTIONS = 1.4
		TRADE = 1.4
		PLAYERTRADE = 1.4
		RCLICKMENU = 1.4

**Comment by ghost** [comment]
2560*1440x32 is fixed.

**Comment by Jestunhi** [comment]
4k is fixed too.
![image](https://user-images.githubusercontent.com/112770725/199928942-b7ce626d-213a-44ba-80af-0ee71d2a2875.png)

Going to close this issue now as seems to be resolved.
