### ISSUE TITLE
Mission XP Incorrect

### ISSUE THREAD

**Issue by Stevil79** [Neocron-Classic/pre-release-issues#20]
Whilst doing Small Sewer Rat missions in Plaza 1 Sewer I noticed I was only getting 37xp instead of 50 per skill per completed mission. This is repeatable. I tried it with my LE chip installed and without. I have not tested any other missions

**Comment by NCC-Therenall** [comment]
This should be fixed in an upcoming patch. The XP multiplier was not being applied to the message being printed out.

**Comment by Stevil79** [comment]
I'm now PSI level 3 on my spy and the XP has gone down to 20 per mission.
