### ISSUE TITLE
Factionname, MASTER was a NC2 Thing?

### ISSUE THREAD

**Issue by hazuk** [Neocron-Classic/pre-release-issues#202]
After Completing a Epic The Character Name gets in the hitbox behind the Factionname a Master Title.
When i remember correctly this was added with NC2.
So all Faction Names should be only Faction name in the hitbox of a character and not a master title behind it when done the epic.

**Comment by NCC-Gnisha** [comment]
The Master title was indeed in Neocron1.

**Comment by hazuk** [comment]
> The Master title was indeed in Neocron1.

okay i played it from first to last day and cant remember this
