### ISSUE TITLE
DoY Tunnel Mobs do too much damage

### ISSUE THREAD

**Issue by Oscar7654** [Neocron-Classic/pre-release-issues#207]
The DoY Tunnel Mobs doing way too much damage at all 3 Levels. You die as a full buffed PPU within seconds.

**Comment by Wilworin** [comment]
We have a new patch now but I could outheal 7 of them at the same time as a hybrid before the patch. So no, they aren't too much damage. If anything, too little.

**Comment by tuxhomer** [comment]
The DoY Tunnels are to get slot enhancer etc.
The slot enhancer are part of the endgame und used to get slot into the rare weapons.
So it should be hart in the DoY Tunnels

**Comment by NCC-Lykos** [comment]
DoY tunnels are meant to be hardcore content. Closed.
