### ISSUE TITLE
Gen Reps taxes are too damn high!

### ISSUE THREAD

**Issue by Robo-Combyte** [Neocron-Classic/pre-release-issues#209]
The Gene Rep seems to display an extremely high price for unlocking it, but it still only takes 150 from your credits.

![image](https://user-images.githubusercontent.com/42428000/196841029-f94b3689-0aa0-4409-bbb4-288380cba467.png)

EDIT: Area in particular was the GR right before heading outside of Neocron. But this one at Battle Dome didn't do the same thing

**Comment by NCC-Lykos** [comment]
This has been fixed in next patch
