### ISSUE TITLE
(Phase 2) Mods increase item stats but do not remove free slots or alter name

### ISSUE THREAD

**Issue by Jestunhi** [Neocron-Classic/pre-release-issues#210]
2 slot weapon bought from vendor. Added 2 mods. Name has not changes, shows 2 slots free, stats have increased.

Mods used: only 2 low tech melee mods available ingame.

![image](https://user-images.githubusercontent.com/112770725/196970984-348fea8f-946e-49b6-a7c8-1051ed737ffb.png)

**Comment by Jestunhi** [comment]
Tried relogging, made no difference. Neither did trading to another character.

![image](https://user-images.githubusercontent.com/112770725/196971227-5652d755-327f-4aaa-967a-3c5192451b28.png)

**Comment by Wilworin** [comment]
It's the same with psi modules.

**Comment by NCC-Therenall** [comment]
Fixed in an upcoming patch
