### ISSUE TITLE
Issues with new player MC5 missions

### ISSUE THREAD

**Issue by Jestunhi** [Neocron-Classic/pre-release-issues#214]
## The problem
The noob MC5 missions have a few issues.

1. The trader NPCs are all-buyers, they have no mission-related dialog. This meant I had no way to complete the mission to give them the cash cube or to get it back.
2. The end of mission text triggers when you have not yet completed the quest, but it does not trigger the quest to end.
3. Hover mower spawns seem to be extremely rare.

### Expected behavior
1. Trader NPC should have mission dialog when you are on a mission which uses them.
2. End of mission text should only trigger when all objectives are complete.
3. enemies for the kill mission should be reliably spawned.

### Steps to duplicate
Create a new character, run the series of missions.

### Screenshots
Please upload any screenshots you believe are relevant to this issue. If it's skill related, post a screenshot of your skills window. Item bug? Post a screenshot of the item. You can drag and drop images into this window.

All 4 of these traders were tried, none has mission dialog.
![image](https://user-images.githubusercontent.com/112770725/197719010-3254c473-24fc-41dd-b8df-3265acff9b4a.png)

For multiple missions in the chain I could get the mission end text to trigger when it was impossible to complete the objectives (mission did not end, rewards were not given).
![image](https://user-images.githubusercontent.com/112770725/197719287-7fe2bfa7-17a8-45d6-8223-c8e6e3c00502.png)

![image](https://user-images.githubusercontent.com/112770725/197719325-6a63d33c-9cb5-420d-91cc-8523e9431db3.png)

**Comment by Vatrasha** [comment]
Only the Trader in the "back" (behind pot as you approach) acted the quest dialog for me, after a relog, and then handed over the package.
If you dont have the "right" quest-NPC arrows on screen right when you accept the quest you can alrdy tell that it is not working as intended.

The mechanical hover bug things are not respawning.

**Comment by NCC-Lykos** [comment]
Fixed spawn and dialog coming too early. Nomad trader could not reproduce issue. Will try restarting zone.
