### ISSUE TITLE
Transport is bugged

### ISSUE THREAD

**Issue by FabioVioli** [Neocron-Classic/pre-release-issues#215]
## The problem
Transport encumbered works on percentages rather than flat numbers.

### Expected behavior
For example, a character with 100 transport would find themselves slowed with 30/40 transport free, going slow as a 0 transport character with 6/7 free.

Just test when the encumbered kicks in with a 0 transport char, a 25 one, a 50 one, etc...
### Screenshots
Can't post a screenshot of me being slowed by the encumbered ( now I have 50 and I am getting slowed when I have 20/30 free transport.

**Comment by Jestunhi** [comment]
"Transport encumbered works on percentages rather than flat numbers."

Was this not always the case, it's how I remember it working.

**Comment by NCC-Therenall** [comment]
Yes, your overloaded movement speed penalty is a gradient, not flat percentage breakpoints. Are you saying there's something wrong with that gradient, or?

Edit: I should say there is a gradient after 75% load. Once you hit 75% load, you get a penalty which is determined by a formula based on load.

**Comment by FabioVioli** [comment]
Understood. 

It's just it feels weird being slowed while having 30 or more transport free. It somehow give less value to transport.
