### ISSUE TITLE
distance cpu values off

### ISSUE THREAD

**Issue by rolikz** [Neocron-Classic/pre-release-issues#216]
Both distance cpu 1 and 2 give the same amount of rifle/pc.

**Comment by ghost** [comment]
I'm showing the following, which is live in-game:

### BioTech Distance Weapon CPU 1
 - Pistol Combat: +3
 - Rifle Combat: +3

### BioTech Distance Weapon CPU 2
 - Pistol Combat: +5
 - Rifle Combat: +5

Both are also giving the proper adjustment within the skill window.

Can you please provide screenshots of where you're seeing this giving the same?

**Comment by ghost** [comment]
Unable to duplicate. Closing this for now.
