### ISSUE TITLE
Vendor Bug

### ISSUE THREAD

**Issue by Liquidous** [Neocron-Classic/pre-release-issues#226]
## The problem
Vendor in D-09 Crest Uplink causes disconnect when you click on an item in it's store.

### Expected behavior
Be able to purchase items

### Steps to duplicate
The Yo's: Outpost supplies vendor 
Use him , click item in list
You disconnect

### Screenshots
Please upload any screenshots you believe are relevant to this issue. If it's skill related, post a screenshot of your skills window. Item bug? Post a screenshot of the item. You can drag and drop images into this window.
![VendorBug](https://user-images.githubusercontent.com/113066151/198866277-8cd9ae31-1291-45be-ae12-9227810ae295.jpg)

**Comment by ghost** [comment]
Fixed.
