### ISSUE TITLE
Unable to cap because missing points and PA access

### ISSUE THREAD

**Issue by FabioVioli** [Neocron-Classic/pre-release-issues#229]
## The problem
With the new skill points system that got rid of several points character used to be, and because of the skill flexibility without any limit ( every character can hit 100 in any skill ) without access to PA from other classes, characters may end up being unable to cap their skills.

I am playing a PE, so I am going to mention this one ( but this goes for every class with 1.0 that attempts to go for a skill. Pistol/rifle tanks, Pistol/rifle monks, etc... )

### Expected behavior

Each class started with 78/40/20/10/2 , distribuited in different skills depends the class.

Back then a monk ( 1.0 modifier ) was able to cap their spells getting 180 APU and PPU.
This because of the 78 starting points in PSI and the PA, which gave them PPU/APU.

The new system % don't take into account neither the missing points, nor the possibility to wear any PA ( or the availability for specific new PAs for each classe, though it would be easier to just remove the class requirement from any PA ).

What we know for sure is that we were able to hit 180 APU or PPU [ 129 ( currently is 119  because of the missing 10 points ) base + 35 from ips ( DEF/OFF 3, DEF/OFF 2, PSI CORE, DIMENSION SPLITTER ) + 16 from PA 3 = 180].pai

Rather than giving extra starting points to a character, to bring back what was the previous balance, I think the easier way would be:

- allow all PA to all classes, rather than creating new ones ( just remove the class requirement, leaving intact the requirements and bonuses )

- reduce the % required to cap by 10 points ( 5 psi level are 25 points with the new system, agains the 78 a Pst character got. Roughly, it could be sum up as 50 points ). But on this one I have no idea what could be the best idea.

### Steps to duplicate
Describe the steps, in detail, that we can take to duplicate this issue.

### Screenshots
Here's a screenshot explaining a little more.
Anyway, I am available for tests ( gonna test with researched PSI modules with 120% dmg, as well as without LE ).
![PE](https://user-images.githubusercontent.com/115998666/198874268-7ba0302b-49f6-4f66-906d-a812850c116c.png)

**Comment by ghost** [comment]
We'll keep this in our thoughts and prayers.
