### ISSUE TITLE
VFX: Projectile: Twilight Guardian Contact Persons 

### ISSUE THREAD

**Issue by ForeverToast** [Neocron-Classic/pre-release-issues#23]
When the Twilight Guardian Contact Persons in Pepper Park Sec 3 attack hostile players part of the VFX from their projectiles hangs and continues to animate.

Issue occurred 10/10.

![image](https://user-images.githubusercontent.com/22384196/188294986-e6f0a94d-cc42-4bce-9352-e1d56bb66f07.png)
![image](https://user-images.githubusercontent.com/22384196/188295043-d813fa05-1099-4663-86ef-0c0994c84bdc.png)
![image](https://user-images.githubusercontent.com/22384196/188295075-522cf555-814a-4918-90dd-64612ae7dbb4.png)

**Comment by hazuk** [comment]
seen this on a cyclops rocket at the j01 bunker too

**Comment by Jestunhi** [comment]
This occurs on other fusion weapons too, not just these NPCs.

**Comment by NCC-Therenall** [comment]
This should be fixed on fusion pistols and rifles.

Is this still happening?

**Comment by ghost** [comment]
I've picked a few fights with those NPCs as well as watching other runners using fusion weapons and have not seen this occurring. I also haven't seen rocket trails from Launcher Cyclopsi.

Going to close this for now.
