### ISSUE TITLE
Missing Name of Conster on Item NCPD 'Cleansing' Flame Thrower

### ISSUE THREAD

**Issue by ghost** [Neocron-Classic/pre-release-issues#233]
## The problem
Rena Chan Const Skill 290 
Missing Name of Conster on Item NCPD 'Cleansing' Flame Thrower

### Steps to duplicate
Construct a NCPD 'Cleansing' Flame Thrower and the Name of the Conster is missing.

### Screenshots
![2](https://user-images.githubusercontent.com/32795552/198930040-cd5eb38a-efd0-4ebf-94f7-6c559ad42c35.jpg)

**Comment by ghost** [comment]
Unable to reproduce. Crafted items must be 3 or more slots for your name to appear. The weapon you posted appears to only be two slots.

![3slots](https://user-images.githubusercontent.com/32779211/198937902-c238cbcf-61ad-413d-9977-e90db7b064b9.png)

**Comment by ghost** [comment]
@NCC-Gnisha maybe add name to 0-3 slots too ?? wtf

**Comment by ghost** [comment]
was my last report im done with ITS NOT A BUG or Unable to reproduce good luck :)

**Comment by xAkinaChanx** [comment]
ahh i forget that the Name only shows when 3 Slots are added too the Items

**Comment by ghost** [comment]
@hazuk 
> was my last report im done with ITS NOT A BUG or Unable to reproduce good luck :)

You created an issue for a **bug**. The name not being on a two slotted weapon is currently in line with how it's set within the code. Therefore, it is not a bug. GitHub Issues is not a place for every runner to post how they think something should be done.

Whether you want to keep putting in bug reports or not is up to you. However, only a handful of the reports that you have created have been closed as "not a bug". The vast majority of issues that you have reported are still waiting to be worked on.
