### ISSUE TITLE
Netcode needs fixing

### ISSUE THREAD

**Issue by thejohnwick** [Neocron-Classic/pre-release-issues#28]
Big red truck in ufail anus
![unknown](https://user-images.githubusercontent.com/36860966/188308481-3208aabd-830a-439c-b1e6-3a3a076e6022.png)

**Comment by NCC-Lykos** [comment]
This is not helpful at all, we are aware of the issues of people overseas. This is first and foremost a US based server and the US based clients do not have as many issues as our EUR players.

Do not troll this issue tracker or I will ban all the EUR players.
