### ISSUE TITLE
Melee Vendors in Plaza Sec - 3 are not positioned correctly.

### ISSUE THREAD

**Issue by ForeverToast** [Neocron-Classic/pre-release-issues#3]
The Melee Vendors in Plaza Sec - 3 are not positioned correctly, and are instead standing next to and or in the Low Tech Cannon Shop next door to where I believe they are meant to be.

![image](https://user-images.githubusercontent.com/22384196/188254161-3595061d-3672-42e6-934a-872c178666fb.png)

![image](https://user-images.githubusercontent.com/22384196/188254233-1d3f2b40-92d6-477b-aabe-c72e6373afea.png)

**Comment by NCC-Lykos** [comment]
Fixed in hotfix.
