### ISSUE TITLE
Medical kits randomly 'break' (stop being usable)

### ISSUE THREAD

**Issue by Jestunhi** [Neocron-Classic/pre-release-issues#34]
This seems to happen completely at random. I'd guess when zoning / traveling via gen rep.

Medical kits will lose the number showing how many uses they have (normally 1 - 3) and become an unusable item. The tooltip is unchanged.

![image](https://user-images.githubusercontent.com/112770725/188327110-5beb1eee-dcc2-4d1d-8c88-da8f47a8524c.png)

**Comment by Jestunhi** [comment]
Just randomly found a first aid kit on the floor that someone dropped as it had the same issue.

**Comment by Jestunhi** [comment]
Happens to repair nanites too.

![image](https://user-images.githubusercontent.com/112770725/188327871-25d449e0-349a-4a30-86fd-026c20365412.png)

**Comment by Dreaminpastels** [comment]
Confirm I had this happening on stamina as well

**Comment by derM4rK** [comment]
as far as i can tell it only happens in quickbelt not in inventory

https://gyazo.com/c20a5a8ad4be7124733675d227a2cddf

**Comment by derM4rK** [comment]
happens only with items in quickbelt and processor afaik. even happend to ammo in processor for me.

**Comment by NCC-Therenall** [comment]
I believe I've fixed this in my item storage rewrite. We'll see I guess.

**Comment by ERnsTL** [comment]
I also noticed this issue today, happening with medkits used from the quickbelt.

**Comment by NCC-Therenall** [comment]
Is this still happening since the item changes have gone live last week?

**Comment by Jestunhi** [comment]
Looks like this is resolved now. It was happening consistently when I would genrep to my apt, but now I've just gone to my apt and back to P1 with medkits & stam boosters in my quickbar, processor and inventory and none of them broke.

**Comment by Jestunhi** [comment]
Seems fixed based on my testing and no one else has come back confirming issues in the 6 days since Therenall asked - closing issue.
