### ISSUE TITLE
Shops: Items: Items shown with Slots can not have them when purchased.

### ISSUE THREAD

**Issue by ForeverToast** [Neocron-Classic/pre-release-issues#38]
When the player buys an item from a merchant that displays it as having slots. The item has a chance to not have any.

Occurred 3/3

This was from the PPU Module vendor in Pepper Park Sec 3

![image](https://user-images.githubusercontent.com/22384196/188332799-9b42e5c4-91bc-46a2-abf9-8dcdaacd07a1.png)
![image](https://user-images.githubusercontent.com/22384196/188332830-9cb0299e-3e4a-43e2-ba80-2d9a91f22f09.png)

**Comment by NCC-Gnisha** [comment]
This has been fixed.
