### ISSUE TITLE
Solider Tank cant use his starter weapon

### ISSUE THREAD

**Issue by Skansy** [Neocron-Classic/pre-release-issues#4]
I Started as a Soldier - Tank and got a str 7 Grenade launcher but Start with str 5

![image](https://user-images.githubusercontent.com/32749567/188258667-e0113874-db26-4e75-b30e-9123b3b22bbc.jpeg)

**Comment by NCC-Gnisha** [comment]
This will be fixed when I push up my next batch of changes.

**Comment by NCC-Gnisha** [comment]
Fixed.
