### ISSUE TITLE
Weapons: Melee: Electroshockers, All of them say they can use the ammo type "City Mercs Construction License"

### ISSUE THREAD

**Issue by ForeverToast** [Neocron-Classic/pre-release-issues#43]
When selecting "More Info" on an Electro Shocker type weapon. They list a compatible ammo type of "City Mercs Construction License"

This was observed on all the Electro Shockers in the Plaza 2 Advanced Weapons Merchants Sell List.

![image](https://user-images.githubusercontent.com/22384196/188341895-a0cbfcc1-8928-4a60-bbdd-1ebbe272be73.png)

**Comment by NCC-Gnisha** [comment]
Fixed.
