### ISSUE TITLE
broken MedKits

### ISSUE THREAD

**Issue by Skansy** [Neocron-Classic/pre-release-issues#46]
i logged into the game and a few Medkits were broken

no charges, cant use
![image](https://user-images.githubusercontent.com/32749567/188483084-138cfa4c-06d0-4cbb-b818-a83810d1d30a.png)

**Comment by Jestunhi** [comment]
Might be better to add supporting comments / screenshots here and close this one: https://github.com/Neocron-Classic/pre-release-issues/issues/34

**Comment by NCC-Lykos** [comment]
Duplicate of #34
