### ISSUE TITLE
TG epic mission 1. Mission text tells the wrong spot for NPCs

### ISSUE THREAD

**Issue by Wilworin** [Neocron-Classic/pre-release-issues#49]
![image](https://user-images.githubusercontent.com/75475031/188488115-8bfcca78-76a1-4c3a-a56b-013a18e97c30.png)

The mission text states that we should meet people at the HQ but it's closed so they are in Yagers.

**Comment by NCC-Gnisha** [comment]
Fixed. Should be in next patch.
