### ISSUE TITLE
Sewer Water = no water

### ISSUE THREAD

**Issue by Skansy** [Neocron-Classic/pre-release-issues#50]
i jumped into the water in a Sewer (Plaza 3) and was able to run in it ... cant swim up :)
its just like air

![image](https://user-images.githubusercontent.com/32749567/188492422-83e7ff23-8e88-452b-a4a3-1be798378577.png)
![image](https://user-images.githubusercontent.com/32749567/188492520-ea90f473-b3e3-4a08-9202-b04bab5ad887.png)

**Comment by ghost** [comment]
This has been fixed.
