### ISSUE TITLE
Items: Drugs: Stamina Booster 1 and 2 display same boost to Stamina.

### ISSUE THREAD

**Issue by ForeverToast** [Neocron-Classic/pre-release-issues#51]
Stamina Booster 1 and 2 both display as regening the same amount of Stamina in the items Show Info screen.

Displayed +255 Stam in both Boosters.

With 136 Stam a Stam Booster 1 completely refilled my stamina.

Unable to test if they are both boosting the same amount or if it is only a description issue.

![image](https://user-images.githubusercontent.com/22384196/188502513-6995394f-997e-48f2-aa8b-71ea03452df9.png)

![image](https://user-images.githubusercontent.com/22384196/188502541-e08ae477-e12e-46da-9ebd-bf74d84046c3.png)

**Comment by NCC-Gnisha** [comment]
Fixed. Submitted for patching.
