### ISSUE TITLE
Dropped a belt with LE in

### ISSUE THREAD

**Issue by Jestunhi** [Neocron-Classic/pre-release-issues#61]
I just died in the aggies in the A&W in Plaza 1 (by the exit to plaza 2) with my LE in and dropped a belt.

![image](https://user-images.githubusercontent.com/112770725/188517888-238a22ad-8a20-4caa-838c-73625d87cd99.png)

**Comment by Jestunhi** [comment]
I don't know what the zone is set to (pve zone, etc) - when I zone down into it there's no message telling me the zone type or rewards / penalties for killing people.

And given that you enter it from P1 which is a safe zone I'd definitely expect a message as it's clearly a different type of zone.

**Comment by hazuk** [comment]
i killed Sato in aggi cellar.. no -sl or -symp
