### ISSUE TITLE
Vendors in TG canyon runs into each other

### ISSUE THREAD

**Issue by Wilworin** [Neocron-Classic/pre-release-issues#7]
![unknown](https://user-images.githubusercontent.com/75475031/188272379-e0e4e736-bfdc-4c3d-b34d-aafc53180c2a.png)

The trade vendors in TG canyon are running into each other. They are simply too many at the same place to fit. Spread them out abit perhaps?

**Comment by NCC-Lykos** [comment]
Please check this again after the latest hotfix.

**Comment by NCC-Lykos** [comment]
Fixed
