### ISSUE TITLE
Trader in H15 Soliko Lab sell wrong Items.

### ISSUE THREAD

**Issue by hazuk** [Neocron-Classic/pre-release-issues#70]
Trader in H15 Soliko Lab sell wrong Items.

![image](https://user-images.githubusercontent.com/32795552/188736047-31c0caab-0b10-4ed1-bff1-7aff0163723c.png)

**Comment by NCC-Gnisha** [comment]
How is this a wrong item? It's a Lab. A lab is researched based. Each OP has a specific Outpost Equipment vendor that sells items relating to the type of outpost.

**Comment by hazuk** [comment]
@NCC-Gnisha in other op´s the same trader name with same name sells hacking tools and stuff.
thats why i was irretated

**Comment by hazuk** [comment]
Selling : Outpost Equipment ... isnt it a Hack tool, Turrets, something like these things?

**Comment by NCC-Gnisha** [comment]
We've reworked a lot of the vendors, and changed up what they sell. Turrets you can buy from the Military Surplus vendor at Military Base.

**Comment by hazuk** [comment]
okay my fault ! :) can be closed^^
