### ISSUE TITLE
Swamp Cave F 03 

### ISSUE THREAD

**Issue by hazuk** [Neocron-Classic/pre-release-issues#72]
in the swamp cave in f03 you can find 2 pictures on the floor near the entrance
![image](https://user-images.githubusercontent.com/32795552/188758105-13f63c30-67d6-4485-b2b0-af4a3bd23beb.png)

![image](https://user-images.githubusercontent.com/32795552/188757988-caa8baf8-7451-4b35-aad2-05ff23210175.png)

**Comment by hazuk** [comment]
and a Private Eye NPC at the end
![image](https://user-images.githubusercontent.com/32795552/188762089-45827ede-36d0-43ab-8523-47eb5ae88369.png)

**Comment by NCC-Gnisha** [comment]
The first image is not a bug. I'll look at that NPC at the end.

**Comment by hazuk** [comment]
why is this dude in the game ?? xD

**Comment by NCC-Gnisha** [comment]
NPC at the end has been removed.
