### ISSUE TITLE
Apartment error in Viarosso 2

### ISSUE THREAD

**Issue by antiteilchen** [Neocron-Classic/pre-release-issues#75]
Apartment error in Viarosso 2 fraction Proto Pharma.
You come out of a different exit.
Entrance E in, exit F out.

![neocron Screenshot 1](https://user-images.githubusercontent.com/113052035/188948428-0b060fbe-22ee-4948-9b36-a3a9058675e6.png)
![neocron Screenshot 2](https://user-images.githubusercontent.com/113052035/188948447-3be6af6e-27e9-4788-b58f-4a6f13b4e192.png)
![neocron Screenshot 3](https://user-images.githubusercontent.com/113052035/188948454-b00717b5-1e07-46ff-97a0-6cad8e516877.png)
![neocron Screenshot 4](https://user-images.githubusercontent.com/113052035/188948466-09c1636c-4c8b-4b7a-9105-78192d17233e.png)
![neocron Screenshot 5](https://user-images.githubusercontent.com/113052035/188948481-3d61c9c2-d331-471b-be52-9795355a5c12.png)
![neocron Screenshot 6](https://user-images.githubusercontent.com/113052035/188948492-8dee7b34-0bff-4560-850c-5fa28fca9ec4.png)
![neocron Screenshot 7](https://user-images.githubusercontent.com/113052035/188948500-899399a4-8820-4377-a993-125a80f048ca.png)
![neocron Screenshot 8](https://user-images.githubusercontent.com/113052035/188948509-3966c9e4-ea7f-4789-bab3-25b5bbbafa79.png)
![neocron Screenshot 9](https://user-images.githubusercontent.com/113052035/188948516-c12501b4-4b09-4055-bf69-e45b5d914e5a.png)

**Comment by ghost** [comment]
Fixed.
