### ISSUE TITLE
Free exp grind in TH SEC-1

### ISSUE THREAD

**Issue by derM4rK** [Neocron-Classic/pre-release-issues#87]
All NPC`s in this Bar :)

https://gyazo.com/5cbfea0afc4c6ac5ac4923ca196fc968

**Comment by hazuk** [comment]
the bar is in th sec 1... there are many npc´s with the no walk feature...
You can get there easy exp with a new th character
Example: create a tank soldier get some granates and go aoe grind these guys till you high enough for better items
