### ISSUE TITLE
Subway Station Viarosso makes you stuck

### ISSUE THREAD

**Issue by hazuk** [Neocron-Classic/pre-release-issues#9]
start at plaza station and drive to viarosso.When you leave the subway at viarosso station you get stuck in a rail 
Outzone to Via works fine! it is only from plaza to via

Hold A+Shift while exit the subway and you stucked
see screenshot
![image](https://user-images.githubusercontent.com/32795552/188272840-12394944-7669-40ea-86ca-43ebb7f1c03f.png)

**Comment by NCC-Lykos** [comment]
Fixed in next patch
